print('Hello Word')
print('3'+'3')
print(3+3)
print('3+3')
print('Ola','134')
nome=input('Qual seu nome?')
idade=input('Qual sua idade?')
altura=input('Qual sua altura?')
print(nome,idade,altura)